### ISSUE TITLE
Day 18 lab - Fix warnings and improve UI

### ISSUE THREAD

**Issue by elaewin** [EvitaAFD/Gogo-Github#5]
Right now you have a couple of warnings that are popping up when I load your app.  You should try to resolve any warnings before you submit the lab. The fixes for those warnings are fairly simple.

Also, in your RepoDetailVC, it's unclear what the data is supposed to be -- I know what each of the labels is for because I can see the code, but if I didn't know, They're not necessarily self-explanatory. Add some text to clarify what data is being presented.

**Comment by EvitaAFD** [comment]
warnings fixed and data labels added.
