### ISSUE TITLE
Day 19 Lab - Missing technical requirement

### ISSUE THREAD

**Issue by elaewin** [EvitaAFD/Gogo-Github#7]
You're still missing the following technical requirement:

* Add a regex extension to String to validate user input into the UISearchBar's of your application.

Obviously, you'll need to add a search bar first. You should be able to get most of the functionality working by watching the class demos from Wednesday and Thursday.

**Comment by EvitaAFD** [comment]
Fixed!

**Comment by elaewin** [comment]
When I search for something using the search bar, the results that show up do not match the string that is in the search bar.

For instance, when I search for "Portfolio", repos titled "Portfolio" do not show up. I also cannot search by number.
